export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_FAILURE = 'FETCH_FAILURE';
export const SET_TEXT_FILTER = 'SET_TEXT_FILTER';
export const SORT_BY_CURRENCY = 'SORT_BY_CURRENCY';
export const SORT_BY_RATE = 'SORT_BY_RATE';
